baseURL: /
title: "Early Fusion Music"
defaultContentLanguage: en
languages:
  en:
    lang: en
    languageName: English
    weight: 1
MetaDataFormat: "yaml"
theme: "nautch"
sectionPagesMenu: mainMenu

markup:
    goldmark:
      renderer:
        unsafe: true
